CREATE DATABASE IF NOT EXISTS #MDB_APPDB# CHARACTER SET #MDB_CHARACTERSET# COLLATE #MDB_COLLATION#;
CREATE USER '#MDB_APPDB_USER#'@'%' IDENTIFIED BY '#MDB_APPDB_PWD#';
GRANT ALL PRIVILEGES ON *.* TO '#MDB_APPDB_USER#'@'%' WITH GRANT OPTION;